version: '3.3'

services:

  frontend:
    container_name: client
    build:
      context: '.'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
      - 6006:6006
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
